server:
  port: ${PORT:8099}

spring:
  application:
    name: travel-api

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

firebase:
  project-id: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}

logging:
  level:
    com.travel: DEBUG
    org.springframework.security: DEBUG
