-- TravelCraft schema migration.
-- Apply with Supabase SQL Editor or `supabase db push`.
-- The application authenticates through Firebase; users.supabase_user_id stores
-- that external subject, so these foreign keys reference public.users.

create table if not exists public.users (
  user_id bigint generated by default as identity primary key,
  supabase_user_id text not null unique,
  user_name text,
  email text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  category_id bigint generated by default as identity primary key,
  user_id bigint references public.users(user_id) on delete cascade,
  category_name text not null
);
alter table public.categories add column if not exists user_id bigint;
alter table public.categories drop constraint if exists categories_user_id_fkey;
alter table public.categories add constraint categories_user_id_fkey
  foreign key (user_id) references public.users(user_id) on delete cascade;

create table if not exists public.trips (
  trip_id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id),
  title text not null,
  trip_date date,
  memo text,
  companions integer,
  share_token text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.trip_members (
  trip_id bigint not null references public.trips(trip_id) on delete cascade,
  user_id bigint not null references public.users(user_id) on delete cascade,
  primary key (trip_id, user_id)
);

create table if not exists public.schedule_items (
  schedule_id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(trip_id) on delete cascade,
  title text not null,
  description text,
  location text,
  start_time timestamptz,
  end_time timestamptz,
  cost numeric(12,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.budget (
  budget_id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(trip_id) on delete cascade,
  user_id bigint references public.users(user_id) on delete cascade,
  category_id bigint not null references public.categories(category_id),
  budget_amount numeric(12,2)
);

-- Upgrade installations that used created_by_user_id before user_id.
alter table public.budget add column if not exists user_id bigint;
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'budget'
      and column_name = 'created_by_user_id'
  ) then
    execute 'update public.budget set user_id = coalesce(user_id, created_by_user_id) where user_id is null';
  end if;
end $$;
update public.budget b
set user_id = t.user_id
from public.trips t
where b.trip_id = t.trip_id and b.user_id is null;
alter table public.budget alter column user_id set not null;
alter table public.budget drop constraint if exists budget_user_id_fkey;
alter table public.budget add constraint budget_user_id_fkey
  foreign key (user_id) references public.users(user_id) on delete cascade;
create index if not exists idx_budget_trip_user on public.budget(trip_id, user_id);

create table if not exists public.expense (
  expense_id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(trip_id) on delete cascade,
  user_id bigint references public.users(user_id) on delete cascade,
  category_id bigint not null references public.categories(category_id),
  expense_amount numeric(12,2) not null,
  expense_date date,
  payment_method text
);

-- Upgrade installations that used created_by_user_id before user_id for expenses.
alter table public.expense add column if not exists user_id bigint;
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'expense'
      and column_name = 'created_by_user_id'
  ) then
    execute 'update public.expense set user_id = coalesce(user_id, created_by_user_id) where user_id is null';
  end if;
end $$;
update public.expense e
set user_id = t.user_id
from public.trips t
where e.trip_id = t.trip_id and e.user_id is null;
alter table public.expense alter column user_id set not null;
alter table public.expense drop constraint if exists expense_user_id_fkey;
alter table public.expense add constraint expense_user_id_fkey
  foreign key (user_id) references public.users(user_id) on delete cascade;

-- Categories are personal master data. Keep the default category names per user,
-- and move legacy budget/expense rows away from old shared category rows.
do $$
declare
  user_rec record;
  category_rec record;
  budget_rec record;
  expense_rec record;
  owned_category_id bigint;
begin
  for user_rec in select user_id from public.users loop
    for category_rec in
      select category_name from (
        values ('交通費'), ('宿泊費'), ('食費'), ('観光・体験'), ('お土産'), ('その他')
      ) default_names(category_name)
      union
      select category_name from public.categories where user_id is null
    loop
      if not exists (
        select 1 from public.categories
        where user_id = user_rec.user_id and category_name = category_rec.category_name
      ) then
        insert into public.categories (user_id, category_name)
        values (user_rec.user_id, category_rec.category_name);
      end if;
    end loop;
  end loop;

  for budget_rec in
    select b.budget_id, b.user_id, c.category_name
    from public.budget b
    join public.categories c on c.category_id = b.category_id
    where b.user_id is not null
      and (c.user_id is null or c.user_id <> b.user_id)
  loop
    select category_id into owned_category_id
    from public.categories
    where user_id = budget_rec.user_id and category_name = budget_rec.category_name
    order by category_id
    limit 1;

    if owned_category_id is not null then
      update public.budget set category_id = owned_category_id
      where budget_id = budget_rec.budget_id;
    end if;
  end loop;

  for expense_rec in
    select e.expense_id, e.user_id, c.category_name
    from public.expense e
    join public.categories c on c.category_id = e.category_id
    where e.user_id is not null
      and (c.user_id is null or c.user_id <> e.user_id)
  loop
    select category_id into owned_category_id
    from public.categories
    where user_id = expense_rec.user_id and category_name = expense_rec.category_name
    order by category_id
    limit 1;

    if owned_category_id is not null then
      update public.expense set category_id = owned_category_id
      where expense_id = expense_rec.expense_id;
    end if;
  end loop;

  delete from public.categories c
  where c.user_id is null
    and not exists (select 1 from public.budget b where b.category_id = c.category_id)
    and not exists (select 1 from public.expense e where e.category_id = c.category_id);

  if not exists (select 1 from public.categories where user_id is null) then
    alter table public.categories alter column user_id set not null;
  end if;
end $$;
create index if not exists idx_categories_user on public.categories(user_id);

create table if not exists public.transportation (
  transportation_id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(trip_id) on delete cascade,
  created_by_user_id bigint references public.users(user_id) on delete cascade,
  transportation_type text,
  departure_place text,
  arrival_place text,
  departure_time timestamptz,
  arrival_time timestamptz,
  fare numeric(12,2)
);

create table if not exists public.accommodation (
  accommodation_id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(trip_id) on delete cascade,
  created_by_user_id bigint references public.users(user_id) on delete cascade,
  accommodation_name text,
  address text,
  check_in date,
  check_out date,
  reservation_number text
);

create table if not exists public.notification (
  notification_id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(trip_id) on delete cascade,
  created_by_user_id bigint references public.users(user_id) on delete cascade,
  reminder text,
  notification_datetime timestamptz,
  notification_type text
);

update public.transportation x set created_by_user_id = t.user_id from public.trips t
where x.trip_id = t.trip_id and x.created_by_user_id is null;
update public.accommodation a set created_by_user_id = t.user_id from public.trips t
where a.trip_id = t.trip_id and a.created_by_user_id is null;
update public.notification n set created_by_user_id = t.user_id from public.trips t
where n.trip_id = t.trip_id and n.created_by_user_id is null;

alter table public.transportation alter column created_by_user_id set not null;
alter table public.accommodation alter column created_by_user_id set not null;
alter table public.notification alter column created_by_user_id set not null;

create index if not exists idx_expense_trip_user on public.expense(trip_id, user_id);
create index if not exists idx_transportation_trip_user on public.transportation(trip_id, created_by_user_id);
create index if not exists idx_accommodation_trip_user on public.accommodation(trip_id, created_by_user_id);
create index if not exists idx_notification_trip_user on public.notification(trip_id, created_by_user_id);
create index if not exists idx_schedule_trip_start on public.schedule_items(trip_id, start_time);
